openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Lab_05 API'
  description: API для пятого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8888
    description: Example server
paths:
  /messages:
    get:
      summary: Чтение информации о сообщениях для пользователя
      responses:
        '200':
          description: Найденные сообщения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        404:
          description: No user found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message:
    get:
      summary: Чтение информации о сообщении
      parameters:
      - name: message_id
        description: Уникальный идентификатор сообщения
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/id'
      responses:
        '200':
          description: Найденное сообщение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/message'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Обновление информации о сообщении
      parameters:
      - name: message_id
        description: Идентификатор сообщения
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: sender_id
        description: Идентификатор отправителя
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: recipient_id
        description: Идентификатор получателя
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: text
        description: Текст сообщения
        in: query
        required: true
        schema:
          type: string
      - name: timestamp
        description: Дата и время сообщения
        in: query
        required: true
        schema:
          type: string
      - name: is_read
        description: Флаг прочитанного сообщения
        in: query
        required: true
        schema:
          type: boolean
          default: False
      - name: type
        description: Тип вложения
        in: query
        required: true
        schema:
          type: string
      - name: url
        description: id url вложения
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор обновлённого сообщения
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка обновления сообщения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового поста
      parameters:
      - name: message_id
        description: Идентификатор сообщения
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: sender_id
        description: Идентификатор отправителя
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: recipient_id
        description: Идентификатор получателя
        in: query
        required: true
        schema:
          type: integer
          default: 1
      - name: text
        description: Текст сообщения
        in: query
        required: true
        schema:
          type: string
      - name: timestamp
        description: Дата и время сообщения
        in: query
        required: true
        schema:
          type: string
      - name: is_read
        description: Флаг прочитанного сообщения
        in: query
        required: true
        schema:
          type: boolean
          default: False
      - name: type
        description: Тип вложения
        in: query
        required: true
        schema:
          type: string
      - name: url
        description: id url вложения
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор добавленного сообщения
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления сообщения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    id:
      description: Уникальный идентификатор сообщения
      type: integer
    messages:
      type: array
      items:
        $ref: '#/components/schemas/messages'
    message:
      type: object
      properties:
        message_id:
          type: integer
        sender_id:
          type: integer
        recipient_id:
          type: integer
        text:
          type: string  
        timestamp:
          type: string
        is_read:
          type: boolean
        attachment:
          type: object
          properties:
            type:
              type: string
            url:
              type: string
              
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:     
      type: http
      scheme: basic
security:
  - bearerAuth: []
  - basicAuth: []